"""
NyayaSahaya — PDF generation service for complaint letters.
"""

import io
import logging
import os
from fpdf import FPDF

logger = logging.getLogger(__name__)

# Path to bundled Unicode font (optional — falls back to built-in)
_FONT_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "fonts")


class PDFService:
    """Generate downloadable PDF documents from complaint text."""

    def generate_complaint_pdf(self, draft_text: str, language: str = "en") -> bytes:
        """
        Convert a complaint draft string into a PDF byte stream.
        For Tamil text, uses a Unicode-capable font if available;
        otherwise falls back to Latin-1 safe rendering.
        """
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=25)
        pdf.add_page()

        # Try to load Unicode font for Tamil support
        font_loaded = False
        if language == "ta":
            font_path = os.path.join(_FONT_DIR, "NotoSansTamil-Regular.ttf")
            if os.path.exists(font_path):
                pdf.add_font("NotoTamil", "", font_path, uni=True)
                pdf.set_font("NotoTamil", size=11)
                font_loaded = True

        if not font_loaded:
            pdf.set_font("Helvetica", size=11)

        # ── Header ───────────────────────────────────────────
        pdf.set_font_size(16)
        pdf.cell(0, 12, "Legal Complaint" if language == "en" else "சட்ட புகார்", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(6)

        # ── Body ─────────────────────────────────────────────
        pdf.set_font_size(11)

        # Clean and encode text safely
        safe_text = self._sanitize_text(draft_text, language, font_loaded)

        pdf.multi_cell(0, 7, safe_text)

        # ── Disclaimer ───────────────────────────────────────
        pdf.ln(10)
        pdf.set_font_size(8)
        pdf.set_text_color(128, 128, 128)
        disclaimer = (
            "Disclaimer: This document was generated by Needhi AI Legal Assistant. "
            "It provides general legal information and is not a substitute for professional "
            "legal advice. Please consult a qualified lawyer before submitting."
        )
        pdf.multi_cell(0, 5, disclaimer)

        return pdf.output()

    @staticmethod
    def _sanitize_text(text: str, language: str, unicode_font: bool) -> str:
        """Make text safe for PDF rendering."""
        if unicode_font:
            return text

        # For non-unicode fonts, replace characters that can't be encoded
        safe = text.encode("latin-1", errors="replace").decode("latin-1")
        return safe
